name = "colony-website"
main = "worker.js"
compatibility_date = "2024-12-01"

# When colony.dev is proxied through Cloudflare, uncomment:
# [route]
# pattern = "colony.dev/*"
# zone_name = "colony.dev"
